### PR TITLE
Maintain a collection of community scripts

### PR DESCRIPTION
**Pull request by projectitis**
These are a collection of Aseprite scripts developed by the community. The collection was started by JJHagger on the [community forums](https://community.aseprite.org/t/aseprite-scripts-collection/3599). They do not have [time anymore](https://community.aseprite.org/t/aseprite-scripts-collection/3599/77) to maintain the list.

This seems like a great place to maintain the list.

Although there could be many improvements made (descriptions of each script, categories, nicer formatting), this is a good place to start, and they can be contributed over time.

Hopefully others will also contribute their scripts here and continue to grow the list!

### CODE REVIEW

**Comment by dacap** [comment]
Hi @projectitis, thanks for the PR but I think this is not the place to put these scripts. This repository is just to keep some examples to start as a guide/tutorial to start creating new scripts.

We'll try to find some kind of solution, I think we need a special repository to act as a register for extensions and start creating a shortcut for the planned store https://github.com/aseprite/aseprite/issues/1928

**Comment by dacap** [comment]
I've just created a new repository and a new issue: https://github.com/aseprite/extensions/issues/1

**Comment by projectitis** [comment]
Thank you. Please close this MR.

I am reformatting the list of scripts and adding a description about each one, and will then submit to the new repo.

**Comment by dacap** [comment]
> I am reformatting the list of scripts and adding a description about each one, and will then submit to the new repo.

Before that I think we have to stablish a format for the DB yet (can be some JSON files). And I'd start small: submit your own extensions and each author should submit their our extension then when everything is working. We can continue the conversation in the `extensions` repository issue.

**Comment by projectitis** [comment]
Ah, I see. The purpose of this MR was just to find an intermediate new home for the list on the forum because the original author doesn't have time to maintain it. But if the DB is not far away we can wait for that instead.

**Comment by projectitis** [comment]
I am hosting/maintaining the list in my own GitHub in the meantime. [See this Aseprite community post for details](https://community.aseprite.org/t/aseprite-scripts-collection/3599/78) :)

**Pull request closed without merging**
